var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "brand": "",
    "releasedate": "",
    "sim": "",
    "dimension": "",
    "weight": "",
    "os": "",
    "screensize": "",
    "screenresolution": "",
    "screentype": "",
    "screenprotection": "",
    "internalmemory": "",
    "ram": "",
    "cardslot": "",
    "processor": "",
    "gpu": "",
    "type": "",
    "front": "",
    "back": "",
    "frontlight": "",
    "backlight": "",
    "frontrecording": "",
    "backrecording": "",
    "bluetooth": "",
    "threeg": "",
    "fourg": "",
    "fiveg": "",
    "radio": "",
    "wifi": "",
    "nfc": "",
    "image": "https://www.christushealth.org/-/media/images/components/defaults/placeholderimage.jpg"
}, {
    "id": 1,
    "title": "Samsung Galaxy A23e",
    "price": "47,599",
    "brand": "../images/samsung logo.png",
    "releasedate": "2022-04-15",
    "sim": "Dual Sim, Dual Standby",
    "dimension": "164.5 x 76.9 x 8.4 mm",
    "weight": "195 g",
    "os": "Android 12 OS",
    "screensize": "6.6 Inches",
    "screenresolution": "1080 x 2408 Pixels",
    "screentype": "TFT display, 16M Colors, Multitouch",
    "screenprotection": "Corning Gorilla Glass 5",
    "internalmemory": "128 GB",
    "ram": "6 GB",
    "cardslot": "microSD Card, (supports up to 1TB)",
    "processor": "Qualcomm SM6225 Snapdragon 680 4G (6 nm)",
    "gpu": "Adreno 610",
    "type": "(Li-Po Non removable), 5000 mAh",
    "front": "8 MP",
    "back": "50 MP + 5 MP + 2 MP + 2MP",
    "frontlight": "N/A",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/samsung a23e.png"
}, {
    "id": 2,
    "title": "Xiaomi Redmi Note 11",
    "price": "Rs.38,999",
    "brand": "../images/xiaomi logo.png",
    "releasedate": "2022-02-10",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "159.9 x 73.9 x 8.1 mm",
    "weight": "179 g",
    "os": "Android 11, MIUI 13",
    "screensize": "6.43 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "LAMOLED Capacitive Touchscreen, Multitouch ",
    "screenprotection": "Corning Gorilla Glass 3",
    "internalmemory": "64/128 GB",
    "ram": "4/6 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "Qualcomm SM6225 Snapdragon 680 4G (6 nm)",
    "gpu": "Adreno 610	",
    "type": "Li-Po 5000 mAh, non-removable",
    "front": "13 MP",
    "back": "50 MP + 8 MP + 2 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps.",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "N/A",
    "wifi": "Yes",
    "nfc": "Yes (market/region dependent)",
    "image": "../images/xiaomi redmi note 11.png"
}, {
    "id": 3,
    "title": "Oppo Reno 7",
    "price": "Rs. 80,000",
    "brand": "../images/oppo logo.png",
    "releasedate": "2021-10-28",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "N/A",
    "weight": "N/A",
    "os": "Android 11",
    "screensize": "N/A",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "OLED Capacitive Touchscreen",
    "screenprotection": "N/A",
    "internalmemory": "256GB",
    "ram": "8/12 GB",
    "cardslot": "N/A",
    "processor": "Dimensity 920",
    "gpu": "Arm Mali-G68",
    "type": "Li-Po  4500 mAh, non-removable",
    "front": "32 MP",
    "back": "50 MP + 8 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "4K@30 fps, 1080p@30/60/120 fps",
    "bluetooth": "Bluetooth 5.1",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "FM radio",
    "wifi": "Wi-Fi Certified 802.11a/b/g/n/ac",
    "nfc": "No",
    "image": "../images/oppo reno 7 pro 5g.png"
}, {
    "id": 4,
    "title": "Oppo F21 Pro 5G",
    "price": "Rs.83,799",
    "brand": "../images/oppo logo.png",
    "releasedate": "2022-05-31",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "159.9 x 73.2 x 7.5 mm",
    "weight": "173 g",
    "os": "Android 12 OS",
    "screensize": "6.43 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "AMOLED",
    "screenprotection": "Schott Xensation glass",
    "internalmemory": "128GB",
    "ram": "8 GB",
    "cardslot": "microSDXC",
    "processor": "Qualcomm SM6375 Snapdragon 695 5G (6 nm)",
    "gpu": "Adreno 619",
    "type": "Li-Po 4500 mAh, non-removable",
    "front": "16 MP",
    "back": "64 MP + 2 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "Yes",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "No",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/oppo f21 pro.png"
}, {
    "id": 5,
    "title": "Samsung Galaxy A73",
    "price": "Rs.121,699",
    "brand": "../images/samsung logo.png",
    "releasedate": "2021-09-30",
    "sim": "Hybrid Dual SIM, Dual Standby, (Nano-SIM)",
    "dimension": "163.7 x 76.1 x 7.6 mm",
    "weight": "181 g",
    "os": "Android 12, One UI 4.1",
    "screensize": "6.7 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "Super AMOLED Capacitive Touchscreen, Multitouch",
    "screenprotection": "Super AMOLED Plus",
    "internalmemory": "256 GB",
    "ram": "8 GB",
    "cardslot": "No",
    "processor": "Snapdragon 778G",
    "gpu": "Adreno 642L",
    "type": "Li-Po 5000 mAh, non-removable",
    "front": "32 MP",
    "back": "108 MP + 12 MP + 5 MP + 5 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "No",
    "backrecording": "4K@30fps, 1080p@30/120fps; gyro-EIS",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "No",
    "wifi": "Yes",
    "nfc": "Yes(market/region dependent)",
    "image": "../images/samsung galaxy a73.png"
}, {
    "id": 6,
    "title": "Samsung Galaxy Tab A7",
    "price": "Rs.32,999",
    "brand": "../images/samsung logo.png",
    "releasedate": "2021-11-17",
    "sim": "No",
    "dimension": "212.5 x 124.7 x 8 mm",
    "weight": "366 g",
    "os": "Android 11",
    "screensize": "	8.7 inches",
    "screenresolution": "800 x 1340",
    "screentype": "	TFT capacitive touchscreen",
    "screenprotection": "N/A",
    "internalmemory": "32GB",
    "ram": "3 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "Octa-core",
    "gpu": "PowerVR GE8320",
    "type": "Non-removable Li-Po 5100mAh",
    "front": "2 MP",
    "back": "8.0 MP",
    "frontlight": "No",
    "backlight": "No",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "v5.0",
    "threeg": "No",
    "fourg": "No",
    "fiveg": "No",
    "radio": "FM Radio",
    "wifi": "Wi-Fi 802.11",
    "nfc": "N/A",
    "image": "../images/samsung tab a7 lite.png"
}, {
    "id": 7,
    "title": "Tecno Spark 8C",
    "price": "Rs.23,699",
    "brand": "../images/tecno logo.png",
    "releasedate": "2022-02-20",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "	164.57× 76 × 8.95",
    "weight": "N/A",
    "os": "Android 11.0 (Go edition)",
    "screensize": "6.6 inches",
    "screenresolution": "720 x 1612 Pixels",
    "screentype": "IPS LCD, 90Hz",
    "screenprotection": "N/A",
    "internalmemory": "64/128 GB",
    "ram": "2/3/4GB",
    "cardslot": "microSDXC",
    "processor": "MTK A22",
    "gpu": "N/A",
    "type": "Li-Po 5000 mAh, non-removable",
    "front": "8 MP",
    "back": "13 MP + QVGA",
    "frontlight": "Yes",
    "backlight": "Yes",
    "frontrecording": "Yes",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/tecno spark 8c.png"
}, {
    "id": 8,
    "title": "Vivo X80",
    "price": "Rs.152,899",
    "brand": "../images/vivo logo.png",
    "releasedate": "2022-05-28",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "164.9 × 75.23 × 8.30 mm",
    "weight": "206g",
    "os": "Funtouch OS 12",
    "screensize": "6.78 Inches",
    "screenresolution": "1080 x 2400 Pixels",
    "screentype": "AMOLED Capacitive Touchscreen, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "256GB",
    "ram": "12 GB",
    "cardslot": "No",
    "processor": "MediaTek Dimensity 9000 (4 nm)",
    "gpu": "Mali-G710 MC10",
    "type": "(Li-Po Non removable), 4500 mAh",
    "front": "32 MP",
    "back": "50 + 12 + 12 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "4K@30fps, 1080p@30fps",
    "backrecording": "4K@30/60fps, 1080p@30/60fps, gyro-EIS",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "Yes",
    "image": "../images/vivo x80.png"
}, {
    "id": 9,
    "title": "Oppo A16",
    "price": "Rs.24,499",
    "brand": "../images/oppo logo.png",
    "releasedate": "2021-09-20",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "163.8 x 75.6 x 8.4 mm",
    "weight": "190 g",
    "os": "Android 11 OS",
    "screensize": "6.52 Inches",
    "screenresolution": "720 x 1600 Pixels",
    "screentype": "IPS LCD Capacitive Touchscreen, 16M Colors, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "32GB",
    "ram": "3 GB",
    "cardslot": "microSD Card, (supports up to 256GB)",
    "processor": "MediaTek Helio G35 (12 nm)",
    "gpu": "PowerVR GE8320",
    "type": "(Li-Po Non removable), 5000 mAh",
    "front": "8 MP",
    "back": "13MP + 2MP + 2MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/oppo a16.png"
}, {
    "id": 10,
    "title": "OPPO Reno 8",
    "price": "Rs. 87,999",
    "brand": "../images/oppo logo.png",
    "releasedate": "2022-12-31",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "N/A",
    "weight": "N/A",
    "os": "Android 12 OS",
    "screensize": "6.4 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "AMOLED Capacitive Touchscreen, Multitouch",
    "screenprotection": "Corning Gorilla Glass",
    "internalmemory": "128GB",
    "ram": "8 GB",
    "cardslot": "microSDXC",
    "processor": "Qualcomm SM8350 Snapdragon 88",
    "gpu": "Adreno 660",
    "type": "(Li-Po Non removable), 4500 mAh",
    "front": "32 MP",
    "back": "64 MP + 8 MP + 2 MP",
    "frontlight": "Yes",
    "backlight": "Yes",
    "frontrecording": "Yes",
    "backrecording": "Yes",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "NO",
    "wifi": "Yes",
    "nfc": "Yes (market/region dependent)",
    "image": "../images/oppo reno 8.png"
}, {
    "id": 11,
    "title": "Samsung Galaxy A13",
    "price": "Rs.39,699",
    "brand": "../images/samsung logo.png",
    "releasedate": "2022-04-26",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "165.1 x 76.4 x 8.8 mm",
    "weight": "195 g",
    "os": "Android 12 OS",
    "screensize": "6.6 Inches",
    "screenresolution": "1080 x 2408 Pixels",
    "screentype": "TFT display, 16M Colors, Multitouch",
    "screenprotection": "Corning Gorilla Glass 5",
    "internalmemory": "64/128 GB",
    "ram": "4 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "Exynos 850",
    "gpu": "Mali-G52 MP1",
    "type": "(Li-Po Non removable), 5000 mAh",
    "front": "8 MP",
    "back": "50 MP + 5 MP + 2 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "No",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/galaxy a13.png"
}, {
    "id": 12,
    "title": "Apple iPhone 13 Pro",
    "price": "Rs.342,000",
    "brand": "../images/apple logo.png",
    "releasedate": "2021-03-24",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "146.7 x 71.5 x 7.7 mm",
    "weight": "204 g",
    "os": "IOS 15",
    "screensize": "6.1 inches",
    "screenresolution": "1170 x 2532 Pixels",
    "screentype": "Super Retina XDR OLED Capacitive Touchscreen, Multitouch",
    "screenprotection": "Scratch-resistant ceramic glass, oleophobic coating",
    "internalmemory": "128/256/512 GB",
    "ram": "8 GB",
    "cardslot": "No",
    "processor": "Apple A15 Bionic (5 nm)",
    "gpu": "Apple GPU (8-core graphics)",
    "type": "(Li-ion Non removable), 3095 mAh",
    "front": "12 MP",
    "back": "12 MP + 12MP + 12 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30/60/120/240fps",
    "backrecording": "1080p@30/60/120/240fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "Yes",
    "wifi": "No",
    "nfc": "Yes",
    "image": "../images/iphone 13 pro.png"
}, {
    "id": 13,
    "title": "Oppo A96",
    "price": "Rs.50,399",
    "brand": "../images/oppo logo.png",
    "releasedate": "2022-03-21",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "164.4 x 75.7 x 8.4 mm",
    "weight": "191 g",
    "os": "ColorOS 11.1",
    "screensize": "6.43 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "IPS LCD Capacitive Touchscreen, 16M Colors, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "128GB",
    "ram": "8 GB",
    "cardslot": "microSDXC",
    "processor": "Qualcomm Snapdragon 680",
    "gpu": "Qualcomm® Adreno GPU 610",
    "type": "(Li-Po Non removable), 5000 mAh",
    "front": "16 MP",
    "back": "50 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "Yes",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "No",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/oppo a96.png"
}, {
    "id": 14,
    "title": "Infinix Hot 11 Play",
    "price": "Rs.26,199",
    "brand": "../images/infinix logo.png",
    "releasedate": "2021-11-16",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "171.8 x 78 x 8.9 mm",
    "weight": "201 g",
    "os": "Android 11 OS",
    "screensize": "6.82 inches",
    "screenresolution": "720 x 1640 Pixels",
    "screentype": "IPS LCD",
    "screenprotection": "N/A",
    "internalmemory": "64GB",
    "ram": "4 GB",
    "cardslot": "microSD Card, (supports up to 512GB)",
    "processor": "Helio G35 Gaming Processor",
    "gpu": "PowerVR GE8320",
    "type": "Li-Po 6000 mAh, non-removable",
    "front": "8 MP",
    "back": "13 MP + AI Lens",
    "frontlight": "Yes",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/hot 11 play.png"
}, {
    "id": 15,
    "title": "Infinix Note 11S",
    "price": "Rs. 40,000",
    "brand": "../images/infinix logo.png",
    "releasedate": "2021-11-02",
    "sim": "N/A",
    "dimension": "173.06 x 78.37 x 8.7mm",
    "weight": "N/A",
    "os": "Android 11",
    "screensize": "6.95 inches",
    "screenresolution": "1080 x 2460 pixels",
    "screentype": "IPS LCD Capacitive Touchscreen, 16M Colors, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "64/128 GB",
    "ram": "4/6/8 GB",
    "cardslot": "N/A",
    "processor": "MediaTek Helio G96",
    "gpu": "ARM G57 MC2",
    "type": "Li-Po 5000 mAh, non-removable",
    "front": "16 MP",
    "back": "50 MP + 2 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "N/A",
    "backrecording": "N/A",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/infinix note 11s.png"
}, {
    "id": 16,
    "title": "Infinix Note 12 G96",
    "price": "Rs.39,749",
    "brand": "../images/infinix logo.png",
    "releasedate": "2022-05-23",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "164.6 x 76.8 x 8 mm",
    "weight": "185 g",
    "os": "Android 12, XOS 10.6",
    "screensize": "6.7 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "AMOLED",
    "screenprotection": "N/A",
    "internalmemory": "128GB",
    "ram": "8 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "Helio G96",
    "gpu": "Mali-G57 MC2",
    "type": "Li-Po 5000 mAh, non-removable",
    "front": "16 MP",
    "back": "50 MP + 2 MP + QVGA",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1440p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/infinix note 12 g96.png"
}, {
    "id": 17,
    "title": "Realme C25s",
    "price": "Rs.30,000",
    "brand": "../images/realme logo.png",
    "releasedate": "2021-06-08",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "164.5 x 75.9 x 9.6mm",
    "weight": "209 g",
    "os": "Android 11 OS",
    "screensize": "6.5 inches",
    "screenresolution": "720 x 1600 pixels",
    "screentype": "IPS LCD Capacitive Touchscreen, 16M Colors, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "64/128 GB",
    "ram": "4 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "MediaTek Helio G85 (12nm)",
    "gpu": "Mali-G52 MC2",
    "type": "(Li-Po Non removable), 6000 mAh",
    "front": "8 MP",
    "back": "48 MP + 2 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/realme c25s.png"
}, {
    "id": 18,
    "title": "Realme 10 Pro",
    "price": "Rs.48999",
    "brand": "../images/realme logo.png",
    "releasedate": "2022-11-02",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "N/A",
    "weight": "N/A",
    "os": "Android 12 OS",
    "screensize": "6.6 inches",
    "screenresolution": "1080 x 2412 pixels",
    "screentype": "AMOLED Capacitive Touchscreen, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "128GB",
    "ram": "6 GB",
    "cardslot": "microSD Card, (supports up to 256GB)",
    "processor": "Qualcomm Snapdragon 695",
    "gpu": "Adreno 619",
    "type": "(Li-Po Non removable), 5000 mAh",
    "front": "16 MP",
    "back": "50 MP + 8 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "Yes",
    "backrecording": "Yes",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "N/A",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/realme 10 pro.png"
}, {
    "id": 19,
    "title": "Realme 9 4G",
    "price": "Rs.58,499",
    "brand": "../images/realme logo.png",
    "releasedate": "2022-07-18",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "160.2 x 73.3 x 8 mm",
    "weight": "178 g",
    "os": "Android 12",
    "screensize": "6.4 inches",
    "screenresolution": "1080 x 2400 Pixels",
    "screentype": "Super AMOLED Capacitive Touchscreen, 16M Colors, Multitouch",
    "screenprotection": "N/A",
    "internalmemory": "128GB",
    "ram": "6/8 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "Snapdragon 680 Processor",
    "gpu": "Adreno 610",
    "type": "(Li-Po Non removable), 5000 mAh",
    "front": "16 MP",
    "back": "108 MP + 8 MP + 2 MP",
    "frontlight": "Yes",
    "backlight": "No",
    "frontrecording": "1080p@30fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/realme 9 4g.png"
}, {
    "id": 20,
    "title": "Samsung Galaxy S22",
    "price": "Rs.200,999",
    "brand": "../images/samsung logo.png",
    "releasedate": "2022-05-10",
    "sim": "Dual Sim, Dual standby (2 Nano-SIMs + eSIM)",
    "dimension": "146 x 70.6 x 7.6 mm",
    "weight": "167 g",
    "os": "Android 12, One UI 4.1",
    "screensize": "6.1 inches",
    "screenresolution": "1080 x 2340 pixels",
    "screentype": "Dynamic AMOLED 2X Capacitive Touchscreen, 1B Colors, Multitouch",
    "screenprotection": "Corning Gorilla Glass Victus",
    "internalmemory": "256GB",
    "ram": "8 GB",
    "cardslot": "No",
    "processor": "Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm)",
    "gpu": "Adreno 730",
    "type": "(Li-ion Non removable), 3700 mAh",
    "front": "10 MP",
    "back": "50 MP + 10 MP + 12 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "4K@30/60fps, 1080p@30fps",
    "backrecording": "8K@24fps, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, stereo sound rec , gyro-EIS",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "N/A",
    "wifi": "Yes",
    "nfc": "Yes",
    "image": "../images/samsung galaxy s22.png"
}, {
    "id": 21,
    "title": "Apple Iphone 14 Pro",
    "price": "430,400",
    "brand": "../images/apple logo.png",
    "releasedate": "2022-07-06",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "168.8 x 76.9 x 8.5 mm",
    "weight": "N/A",
    "os": "IOS 16",
    "screensize": "6.8 inches",
    "screenresolution": "1080 x 2460 pixels",
    "screentype": "	Retina Display / IPS LCD",
    "screenprotection": "	N/A",
    "internalmemory": "128/256/512 GB",
    "ram": "8 GB",
    "cardslot": "Unspecified",
    "processor": "Apple A15 Bionic (5 nm)",
    "gpu": "Apple GPU (8-core graphics)",
    "type": "Li-Po 5000 mAh, non-removable",
    "front": "24 MP",
    "back": "48 MP + 2 MP + QVGA",
    "frontlight": "Yes",
    "backlight": "Yes",
    "frontrecording": "1080p@30/60/120/240fps",
    "backrecording": "1080p@30fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "Yes",
    "image": "../images/iphone 14 pro.png"
}, {
    "id": 22,
    "title": "Tecno Camon 18 Premier",
    "price": "Rs.51,599",
    "brand": "../images/tecno logo.png",
    "releasedate": "2021-11-20",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "163.8 x 75.9 x 8.2 mm",
    "weight": "200.6 g",
    "os": "Android 11, HIOS 8.0",
    "screensize": "6.7 inches",
    "screenresolution": "1080 x 2400 pixels",
    "screentype": "120Hz FHD+ AMOLED Display",
    "screenprotection": "N/A",
    "internalmemory": "256 GB",
    "ram": "8 GB",
    "cardslot": "microSDXC (dedicated slot)",
    "processor": "Mediatek Helio G96",
    "gpu": "Mali-G57 MC2",
    "type": "Li-Po 4750 mAh, non-removable",
    "front": "32 MP",
    "back": "64MP + 12MP + 08MP",
    "frontlight": "Yes",
    "backlight": "Yes",
    "frontrecording": "1080p@30fps",
    "backrecording": "4K@30fps, 1080p@30fps, gyro-EIS",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "FM radio",
    "wifi": "Yes",
    "nfc": "Yes",
    "image": "../images/tecno camon premiere.png"
}, {
    "id": 23,
    "title": "Huawei Enjoy 10",
    "price": "Rs.32,999",
    "brand": "../images/huawei logo.png",
    "releasedate": "Nano-SIM , Dual Sim",
    "sim": "Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "6.44x 3.04x 0.35in",
    "weight": "196 g",
    "os": "Android 9.0 Pie;EMUI 9.0",
    "screensize": "6.59 inches",
    "screenresolution": "1080 x 2340 pixels",
    "screentype": "IPS Capacitive, Multi-touch",
    "screenprotection": "Capacitive, Multi-touch",
    "internalmemory": "128GB",
    "ram": "4 GB",
    "cardslot": "microSD, microSDHC, microSDXC",
    "processor": "4x 2.2 GHz ARM Cortex-A73, 4x 1.7 GHz ARM Cortex-A53",
    "gpu": "ARM Mali-G51 MP4",
    "type": "Non-removable Li-Polymer 4000 mAh",
    "front": "16 MP",
    "back": "",
    "frontlight": "Yes",
    "backlight": "No",
    "frontrecording": "0 MP",
    "backrecording": "2 MP",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/huawei enjoy 10.png"
}, {
    "id": 24,
    "title": "Huawei Honor 8S",
    "price": "Rs.15,999",
    "brand": "../images/huawei logo.png",
    "releasedate": "2022-03-14",
    "sim": "Nano-SIM , Dual Sim",
    "dimension": "5.79 x 2.79 x 0.33 in",
    "weight": "146 g",
    "os": "Android 9.0 Pie;EMUI 9.0",
    "screensize": "5.71 inches",
    "screenresolution": "720 x 1520 pixels",
    "screentype": "IPS Capacitive, Multi-touch",
    "screenprotection": "Capacitive, Multi-touch",
    "internalmemory": "32GB",
    "ram": "2 GB",
    "cardslot": "microSD, microSDHC, microSDXC",
    "processor": "ARM Cortex-A53",
    "gpu": "PowerVR GE8300",
    "type": "Non-removable Li-Polymer 3020 mAh",
    "front": "5 MP",
    "back": "13 MP",
    "frontlight": "",
    "backlight": "Yes",
    "frontrecording": "2 MP",
    "backrecording": "2 MP",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "No",
    "radio": "Yes",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/huawei honor 8s.png"
}, {
    "id": 25,
    "title": "Huawei Nova 9",
    "price": "Rs.98,999",
    "brand": "../images/huawei logo.png",
    "releasedate": "2022-04-01",
    "sim": "Single SIM (Nano-SIM) or Dual SIM (Nano-SIM, dual stand-by)",
    "dimension": "160 x 73.7 x 7.8 mm",
    "weight": "175 g",
    "os": "HarmonyOS 2.0 (China)",
    "screensize": "6.57 inches",
    "screenresolution": "1080 x 2340 pixels",
    "screentype": "OLED, 1B colors, 120Hz, HDR10",
    "screenprotection": "Corning Gorilla Glass",
    "internalmemory": "128/256 GB",
    "ram": "8 GB",
    "cardslot": "No",
    "processor": "Qualcomm Snapdragon™ 778G 4G",
    "gpu": "Adreno 642L",
    "type": "Li-Po 4300 mAh, non-removable",
    "front": "32 MP",
    "back": "50 MP + 8 MP + 2 MP + 2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "4K@30fps, 1080p@30fps, 720p@240fps, gyro-EIS",
    "backrecording": "4K, 1080p, 720p@960fps, gyro-EISs",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "Yes",
    "fiveg": "Yes",
    "radio": "No",
    "wifi": "Yes",
    "nfc": "Yes",
    "image": "../images/huawei nova 9.png"
}, {
    "id": 26,
    "title": "Nokia 3310",
    "price": "Rs. 8,199",
    "brand": "../images/huawei logo.png",
    "releasedate": "2017-01-01",
    "sim": "Single SIM (Micro-SIM) or Dual SIM (Micro-SIM, dual stand-by)",
    "dimension": "4.55 x 2.01 x 0.50 in",
    "weight": "85 g",
    "os": "No",
    "screensize": "2.4 inches",
    "screenresolution": "240 x 320 pixels",
    "screentype": "TFT",
    "screenprotection": "Corning Glass",
    "internalmemory": "16MB",
    "ram": "16MB",
    "cardslot": "microSD, up to 32 GB (dedicated slot)",
    "processor": "No",
    "gpu": "N/A",
    "type": "Li-ion Non removable 1200mah",
    "front": "No",
    "back": "2 MP",
    "frontlight": "No",
    "backlight": "Yes",
    "frontrecording": "No",
    "backrecording": "240p@8fps",
    "bluetooth": "Yes",
    "threeg": "Yes",
    "fourg": "No",
    "fiveg": "No",
    "radio": "FM Radio",
    "wifi": "Yes",
    "nfc": "No",
    "image": "../images/huawei nova 9.png"
}]